### PR TITLE
added line to install gseapy package

### PR DESCRIPTION
**Pull request by eleanorwilliams**
for GeneAndPhenotypeQueries notebook

I'm not sure if this is the latest Docker file that I have added this to.

### CODE REVIEW

**Comment by manics** [comment]
Can we sort out the other PRs:
- First #17
- Then #13 
before making additional changes?

**Comment by manics** [comment]
This is already in the python2 environment on the develop branch https://github.com/IDR/jupyter-docker/blob/develop/Dockerfile#L43

**Comment by eleanorwilliams** [comment]
@manics  - should i close this PR then?

**Comment by joshmoore** [comment]
Done.

**Pull request closed without merging**
