### PR TITLE
Bump to OMERO 5.4

### PR DESCRIPTION
**Pull request by joshmoore**
For testing. Will move to 5.4.5 once released.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#344](https://ci.openmicroscopy.org/job/DOCKER-merge/344/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/344/consoleText) for more details.
Possible conflicts:
  - PR #26 manics 'OME Jupyterhub 0.8 notebook base-image'
    - test.sh
    - test_notebooks.py
    - environment-python2.yml

--conflicts

**Comment by manics** [comment]
Following https://github.com/IDR/jupyter-docker/pull/26#issuecomment-379346297 can we close this for now?

**Comment by joshmoore** [comment]
We're now aiming to release these together, right? If we're conflicting, can you cherry-pick the commits to the correct location?

**Comment by manics** [comment]
> We're now aiming to release these together, right? If we're conflicting, can you cherry-pick the commits to the correct location?

Not quite, the VAE is live now so we should test it against current idr-prod, then update to 5.4 when idr-prod is updated. The "official" release will probably be done together though.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#345](https://ci.openmicroscopy.org/job/DOCKER-merge/345/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/345/consoleText) for more details.
Possible conflicts:
  - PR #26 manics 'OME Jupyterhub 0.8 notebook base-image'
    - test.sh
    - test_notebooks.py
    - environment-python2.yml

--conflicts

**Pull request closed without merging**
