### PR TITLE
Edited Dockerfile to point to eleanorwilliams/idr-notebooks.git EMBLP…

### PR DESCRIPTION
**Pull request by eleanorwilliams**
…redoc2017Notebooks branch

Please wait until the content of https://github.com/IDR/idr-notebooks/pull/46 is signed off.

This Dockerfile is for the idr-training/jupyter server.

### CODE REVIEW

**Comment by eleanorwilliams** [comment]
@manics PR https://github.com/IDR/jupyter-docker/pull/13 should also be included in the notebook deployment.  Not sure how we say we want https://github.com/IDR/jupyter-docker/pull/13 and this current PR in the deployment for the idr-training server.

**Comment by bramalingam** [comment]
@eleanorwilliams : please add quotes and check if travis passes : 

`/bin/sh -c "..." `

**Comment by eleanorwilliams** [comment]
Now passing travis tests.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#199](https://ci.openmicroscopy.org/job/DOCKER-merge/199/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/199/consoleText) for more details.
Possible conflicts:
  - PR #13 manics 'Add and enable nbresuse for displaying memory usage, add idr-py to dependencies'
    - Dockerfile

~~--conflicts~~ Conflict resolved in build [DOCKER-merge#200](https://ci.openmicroscopy.org/job/DOCKER-merge/200/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/200/consoleText) for more details.

**Comment by sbesson** [comment]
See https://github.com/IDR/idr-notebooks/pull/46#issuecomment-347924262

**Pull request closed without merging**
